-- 새 실습 스키마 전용. 기존 테이블을 DROP하거나 데이터를 삭제하지 않는다.
CREATE TABLE SAMPLE (
    ID VARCHAR(16) PRIMARY KEY,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    USE_YN CHAR(1),
    REG_USER VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IDS (
    TABLE_NAME VARCHAR(16) PRIMARY KEY,
    NEXT_ID DECIMAL(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 데이터 이전 시 SAMPLE 데이터와 IDS.NEXT_ID를 함께 복사한다.
-- 빈 DB에서 시작할 때만 다음 문장을 수동 실행한다.
-- INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('SAMPLE', 1);
